### ISSUE TITLE
weather_level_adj page "Status" field showing python error

### ISSUE THREAD

**Issue by Materdaddy** [Dan-in-CA/ospi_plugins#1]
I received a couple of notices of more than 500 requests to wunderground over the last couple weeks so I updated my OSPi repo the other day.  Upon doing that, I had to separately enable the ospi plugins I use: weather_adj and weather_level_adj.

Now I went to configure weather_level_adj and see this in the Status text box:

<pre>
Weather-base water level encountered error:
Traceback (most recent call last):
  File "/home/pi/ospi/plugins/weather_level_adj.py", line 85, in run
    history = history_info()
  File "/home/pi/ospi/plugins/weather_level_adj.py", line 320, in history_info
    'humidity': float(day_info['humidity'])
ValueError: could not convert string to float: 
</pre>

**Comment by Dan-in-CA** [comment]
Thanks for the bug report. I'll check into it shortly.
I don't like to make such drastic changes to the software but sometimes the results are worth it.

**Comment by Materdaddy** [comment]
It seems the Wunderground API can return empty values for "humidity".  One of my files has "humidity":"" in the JSON data.

<pre>
pi@puppets ~/ospi/data/weather_level_history $ grep humidity history*/*/*
history_20150217/q/zmw:92049.1.99999.json:		"fog":"0","rain":"0","snow":"0","snowfallm":"0.00", "snowfalli":"0.00",
"monthtodatesnowfallm":"0.00", "monthtodatesnowfalli":"0.00","since1julsnowfallm":"0.00", "since1julsnowfalli":"0.00",
"snowdepthm":"0.00", "snowdepthi":"0.00","hail":"0","thunder":"0","tornado":"0","meantempm":"17", "meantempi":"63",
"meandewptm":"10", "meandewpti":"50","meanpressurem":"1019", "meanpressurei":"30.08","meanwindspdm":"8", "meanwindspdi":"5",
"meanwdire":"","meanwdird":"294","meanvism":"12", "meanvisi":"8", <strong>"humidity":""</strong>,"maxtempm":"19", "maxtempi":"67",
"mintempm":"14", "mintempi":"58","maxhumidity":"86","minhumidity":"58","maxdewptm":"12", "maxdewpti":"53","mindewptm":"7",
"mindewpti":"44","maxpressurem":"1020", "maxpressurei":"30.13","minpressurem":"1017", "minpressurei":"30.04","maxwspdm":"19",
"maxwspdi":"12","minwspdm":"0", "minwspdi":"0","maxvism":"16", "maxvisi":"10","minvism":"3", "minvisi":"2","gdegreedays":"6",
"heatingdegreedays":"2","coolingdegreedays":"0","precipm":"0.00", "precipi":"0.00","precipsource":"",
"heatingdegreedaysnormal":"11","monthtodateheatingdegreedays":"97","monthtodateheatingdegreedaysnormal":"187",
"since1sepheatingdegreedays":"","since1sepheatingdegreedaysnormal":"","since1julheatingdegreedays":"783",
"since1julheatingdegreedaysnormal":"1292","coolingdegreedaysnormal":"0","monthtodatecoolingdegreedays":"0",
"monthtodatecoolingdegreedaysnormal":"0","since1sepcoolingdegreedays":"","since1sepcoolingdegreedaysnormal":"",
"since1jancoolingdegreedays":"0","since1jancoolingdegreedaysnormal":"0" }
</pre>

**Comment by Materdaddy** [comment]
Fixed with 805f694.
