### ISSUE TITLE
Using GPIO pins in plugin thread

### ISSUE THREAD

**Issue by Tails86** [Dan-in-CA/ospi_plugins#10]
I have a plugin which uses GPIO pins. It works fine on a normal boot. However, when the system restarts, it causes exceptions within my plugin when the pins are being accessed. I have to catch those exceptions and assume that the software must be restarting. Then I wait for a moment of time before trying to reinitialize pins and continue. Is there a way to synchronize with the system during restart or pin access?

**Comment by Dan-in-CA** [comment]
Would adding a program restart signal be something you could use for this?

**Comment by Tails86** [comment]
Yes, that seems like it would help. If my plugin could get a signal that the system is restarting just before cleanup, my plugin would be able to safely close out its thread. That would be a good solution for issue #9 too as the plugin would not be loaded again if it was disabled.

**Comment by Dan-in-CA** [comment]
OK, I'll work on adding a "restart" signal.

**Comment by Dan-in-CA** [comment]
I pushed an update to the main program repo with a restart signal added.
There is a short time delay after the signal is sent (default 1 sec.) before the actual restart happens.

**Comment by Tails86** [comment]
I'm catching the restart signal now and stopping my thread safely, but the system doesn't call my plugin file after restart is complete. If my plugin is originally disabled when the system starts and then enabled, it isn't called at that point either. Am I misunderstanding something?

**Comment by Dan-in-CA** [comment]
The enabled plugins are loaded when the main program starts. If a plugin is enabled after the program has started a restart is necessary in order for the plugin to be loaded.

**Comment by Tails86** [comment]
I thought that is what happens when I click "UPDATE ENABLED" on the plugins page. Below are the steps that I am following.
-Plugin originally disabled on start
-Go to plugins page, select check box next to plugin, select "UPDATE ENABLED"
-Terminal shows that the system is restarting
    Restarting...
(Main function never called in the enabled plugin file after restart is complete)
-Reboot
(Main function is now called in the enabled plugin file)

**Comment by Dan-in-CA** [comment]
Are you starting the program from the command line? If this is the case, the restart button in the UI will not actually restart the program. It uses the init.d script to do the restart.
You would need to stop the program with ctrl + C then relaunch it from the command line.
See the instructions on the wiki for starting the program automatically (The recommended method) near the bottom of the page:
https://github.com/Dan-in-CA/OSPi/wiki/Installation

**Comment by Tails86** [comment]
I tried installing ospi.sh as a service called sip, but of course it didn't work until I renamed it ospi. Having the restart signal solves this issue when the service is installed properly, so I am closing it.

**Comment by Tails86** [comment]
Thanks for your help, Dan
