### ISSUE TITLE
Relay plugin fails to load

### ISSUE THREAD

**Issue by sbrown4** [Dan-in-CA/ospi_plugins#7]
On startup, I get the following:

Ignoring exception while loading the relay plug-in.
cannot import name pin_relay
plugins loaded:
  lcd_adj
  mobile_app
  pcf_8591_adj
  plugin_manager
  proto
  signaling_examples
  system_update
Starting timing loop

I'm running 2.2.38 on a RPi.
Steve

**Comment by Dan-in-CA** [comment]
The relay_board plugin loads on my test system. There may be a conflict with the lcd_adj or pcs_8591 plugin. Try disabling one or both of those.

**Comment by sbrown4** [comment]
I'm having trouble with the relay plugin, not the relay_board plugin.

Cloned a fresh copy of ospi and only downloaded and enabled the relay
plugin.

Ignoring exception while loading the relay plug-in.
cannot import name pin_relay
plugins loaded:
  mobile_app
  plugin_manager
  signaling_examples
  system_update
Starting timing loop

Similar results.

Then I stripped everything out and same results:

Ignoring exception while loading the relay plug-in.
cannot import name pin_relay
plugins loaded:
  plugin_manager
Starting timing loop

Any more ideas?

Steve

**Comment by Dan-in-CA** [comment]
Woops! I misread your first post, sorry.
The problem was in the gpio_pins.py file. It has been fixed now. You should be able to update your installation and the relay plugin should work.
