### ISSUE TITLE
Disabling plugin - how can I catch that event?

### ISSUE THREAD

**Issue by Tails86** [Dan-in-CA/ospi_plugins#9]
I'm not really sure how to be handling when a plugin is disabled. My plugin spawns a separate thread, so I need to be signaled when the plugin should be shut down so I can exit my thread. How should I be handling that? Is that in a value changed signal?

**Comment by Dan-in-CA** [comment]
Plugins are dis/enabled by the plugins plugin. Right now there is no signal to indicate a change. The plugins are dis/enabled by setting the group permission on the plugin's .py file and then the main program is restarted to load the enabled plugins.
We could (probably should) add a signal when the program is being restarted. You could then check the permission of your plugin. Here is some info on doing that:
http://stackoverflow.com/questions/1861836/checking-file-permissions-in-linux-with-python

**Comment by Tails86** [comment]
Dan added a restart signal to resolve this issue. See issue #10
